import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "./components/ui/Footer";
import { BackgroundBeams } from "./components/ui/BackgroundBeams";
import SideNav from "./components/ui/side-nav/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gradient-to-r from-[#0a0e14] to-[#262c35]`}
      >
        <div className="lg:flex">
          <SideNav />
          <div className="relative z-10 basis-10/12 h-screen overflow-y-auto">
            <main>{children}</main>
            <Footer />
          </div>
        </div>
        <BackgroundBeams />
      </body>
    </html>
  );
}
